/*
 * Private API
 * Assessment Private API - Do not use!
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AbstractApp;
import java.io.File;
import io.swagger.client.model.ModelAPIException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppsApi
 */
@Ignore
public class AppsApiTest {

    private final AppsApi api = new AppsApi();

    /**
     * Shows information about a specific app
     *
     * Shows information about a specific app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstalledAppInfoTest() throws ApiException {
        Integer devid = null;
        String appid = null;
        AbstractApp response = api.getInstalledAppInfo(devid, appid);

        // TODO: test validations
    }
    /**
     * Lists installed apps
     *
     * Lists installed apps
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstalledAppsTest() throws ApiException {
        Integer devid = null;
        List<AbstractApp> response = api.getInstalledApps(devid);

        // TODO: test validations
    }
    /**
     * Installs an app
     *
     * Uploads a file and installs it as an app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void installApplicationTest() throws ApiException {
        Integer devid = null;
        File file = null;
        AbstractApp response = api.installApplication(devid, file);

        // TODO: test validations
    }
    /**
     * Uninstalls an app
     *
     * Uninstalls an app
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uninstallApplicationTest() throws ApiException {
        Integer devid = null;
        String appid = null;
        File file = null;
        AbstractApp response = api.uninstallApplication(devid, appid, file);

        // TODO: test validations
    }
}
