/*
 * Private API
 * Assessment Private API - Do not use!
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AbstractApp;
import io.swagger.client.model.ModelAPIException;
import io.swagger.client.model.SavedEnvironment;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeviceEnvironmentsApi
 */
@Ignore
public class DeviceEnvironmentsApiTest {

    private final DeviceEnvironmentsApi api = new DeviceEnvironmentsApi();

    /**
     * Returns a list of saved states
     *
     * List of saved environment states
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStatesTest() throws ApiException {
        Integer devid = null;
        List<SavedEnvironment> response = api.listStates(devid);

        // TODO: test validations
    }
    /**
     * Loads the saved state
     *
     * Loads the saved state
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loadStateTest() throws ApiException {
        Integer devid = null;
        String saveName = null;
        AbstractApp response = api.loadState(devid, saveName);

        // TODO: test validations
    }
    /**
     * Saves the current state as the new saved state
     *
     * Saves the state
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveStateTest() throws ApiException {
        Integer devid = null;
        String saveName = null;
        AbstractApp response = api.saveState(devid, saveName);

        // TODO: test validations
    }
}
