/*
 * Private API
 * Assessment Private API - Do not use!
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.AbstractApp;
import io.swagger.client.model.ModelAPIException;
import io.swagger.client.model.SavedEnvironment;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeviceEnvironmentsApi {
    private ApiClient apiClient;

    public DeviceEnvironmentsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DeviceEnvironmentsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for deleteState
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteStateCall(Integer devid, String saveName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/devices/{devid}/environments/{saveName}"
            .replaceAll("\\{" + "devid" + "\\}", apiClient.escapeString(devid.toString()))
            .replaceAll("\\{" + "saveName" + "\\}", apiClient.escapeString(saveName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteStateValidateBeforeCall(Integer devid, String saveName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'devid' is set
        if (devid == null) {
            throw new ApiException("Missing the required parameter 'devid' when calling deleteState(Async)");
        }
        // verify the required parameter 'saveName' is set
        if (saveName == null) {
            throw new ApiException("Missing the required parameter 'saveName' when calling deleteState(Async)");
        }
        
        com.squareup.okhttp.Call call = deleteStateCall(devid, saveName, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Deletes the current state as the new saved state
     * Saves the state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @return AbstractApp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AbstractApp deleteState(Integer devid, String saveName) throws ApiException {
        ApiResponse<AbstractApp> resp = deleteStateWithHttpInfo(devid, saveName);
        return resp.getData();
    }

    /**
     * Deletes the current state as the new saved state
     * Saves the state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @return ApiResponse&lt;AbstractApp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AbstractApp> deleteStateWithHttpInfo(Integer devid, String saveName) throws ApiException {
        com.squareup.okhttp.Call call = deleteStateValidateBeforeCall(devid, saveName, null, null);
        Type localVarReturnType = new TypeToken<AbstractApp>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Deletes the current state as the new saved state (asynchronously)
     * Saves the state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteStateAsync(Integer devid, String saveName, final ApiCallback<AbstractApp> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteStateValidateBeforeCall(devid, saveName, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AbstractApp>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for listStates
     * @param devid The id of device (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listStatesCall(Integer devid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/devices/{devid}/environments"
            .replaceAll("\\{" + "devid" + "\\}", apiClient.escapeString(devid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listStatesValidateBeforeCall(Integer devid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'devid' is set
        if (devid == null) {
            throw new ApiException("Missing the required parameter 'devid' when calling listStates(Async)");
        }
        
        com.squareup.okhttp.Call call = listStatesCall(devid, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Returns a list of saved states
     * List of saved environment states
     * @param devid The id of device (required)
     * @return List&lt;SavedEnvironment&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<SavedEnvironment> listStates(Integer devid) throws ApiException {
        ApiResponse<List<SavedEnvironment>> resp = listStatesWithHttpInfo(devid);
        return resp.getData();
    }

    /**
     * Returns a list of saved states
     * List of saved environment states
     * @param devid The id of device (required)
     * @return ApiResponse&lt;List&lt;SavedEnvironment&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<SavedEnvironment>> listStatesWithHttpInfo(Integer devid) throws ApiException {
        com.squareup.okhttp.Call call = listStatesValidateBeforeCall(devid, null, null);
        Type localVarReturnType = new TypeToken<List<SavedEnvironment>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns a list of saved states (asynchronously)
     * List of saved environment states
     * @param devid The id of device (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listStatesAsync(Integer devid, final ApiCallback<List<SavedEnvironment>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listStatesValidateBeforeCall(devid, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<SavedEnvironment>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for loadState
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call loadStateCall(Integer devid, String saveName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/devices/{devid}/environments/{saveName}/load"
            .replaceAll("\\{" + "devid" + "\\}", apiClient.escapeString(devid.toString()))
            .replaceAll("\\{" + "saveName" + "\\}", apiClient.escapeString(saveName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call loadStateValidateBeforeCall(Integer devid, String saveName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'devid' is set
        if (devid == null) {
            throw new ApiException("Missing the required parameter 'devid' when calling loadState(Async)");
        }
        // verify the required parameter 'saveName' is set
        if (saveName == null) {
            throw new ApiException("Missing the required parameter 'saveName' when calling loadState(Async)");
        }
        
        com.squareup.okhttp.Call call = loadStateCall(devid, saveName, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Loads the saved state
     * Loads the saved state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @return AbstractApp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AbstractApp loadState(Integer devid, String saveName) throws ApiException {
        ApiResponse<AbstractApp> resp = loadStateWithHttpInfo(devid, saveName);
        return resp.getData();
    }

    /**
     * Loads the saved state
     * Loads the saved state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @return ApiResponse&lt;AbstractApp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AbstractApp> loadStateWithHttpInfo(Integer devid, String saveName) throws ApiException {
        com.squareup.okhttp.Call call = loadStateValidateBeforeCall(devid, saveName, null, null);
        Type localVarReturnType = new TypeToken<AbstractApp>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Loads the saved state (asynchronously)
     * Loads the saved state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call loadStateAsync(Integer devid, String saveName, final ApiCallback<AbstractApp> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = loadStateValidateBeforeCall(devid, saveName, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AbstractApp>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for saveState
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call saveStateCall(Integer devid, String saveName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/devices/{devid}/environments/{saveName}"
            .replaceAll("\\{" + "devid" + "\\}", apiClient.escapeString(devid.toString()))
            .replaceAll("\\{" + "saveName" + "\\}", apiClient.escapeString(saveName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "APIKey" };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call saveStateValidateBeforeCall(Integer devid, String saveName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'devid' is set
        if (devid == null) {
            throw new ApiException("Missing the required parameter 'devid' when calling saveState(Async)");
        }
        // verify the required parameter 'saveName' is set
        if (saveName == null) {
            throw new ApiException("Missing the required parameter 'saveName' when calling saveState(Async)");
        }
        
        com.squareup.okhttp.Call call = saveStateCall(devid, saveName, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Saves the current state as the new saved state
     * Saves the state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @return AbstractApp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public AbstractApp saveState(Integer devid, String saveName) throws ApiException {
        ApiResponse<AbstractApp> resp = saveStateWithHttpInfo(devid, saveName);
        return resp.getData();
    }

    /**
     * Saves the current state as the new saved state
     * Saves the state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @return ApiResponse&lt;AbstractApp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<AbstractApp> saveStateWithHttpInfo(Integer devid, String saveName) throws ApiException {
        com.squareup.okhttp.Call call = saveStateValidateBeforeCall(devid, saveName, null, null);
        Type localVarReturnType = new TypeToken<AbstractApp>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Saves the current state as the new saved state (asynchronously)
     * Saves the state
     * @param devid The id of device (required)
     * @param saveName The id of device (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call saveStateAsync(Integer devid, String saveName, final ApiCallback<AbstractApp> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = saveStateValidateBeforeCall(devid, saveName, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<AbstractApp>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
