/*
 * Private API
 * Assessment Private API - Do not use!
 *
 * OpenAPI spec version: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Permission requsted at runtime
 */
@Schema(description = "Permission requsted at runtime")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-12-21T16:25:16.578+01:00[Europe/Berlin]")public class AndroidPermission {

  @SerializedName("name")
  private String name = null;

  @SerializedName("granted")
  private Boolean granted = null;
  public AndroidPermission name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public AndroidPermission granted(Boolean granted) {
    this.granted = granted;
    return this;
  }

  

  /**
  * Get granted
  * @return granted
  **/
  @Schema(description = "")
  public Boolean isGranted() {
    return granted;
  }
  public void setGranted(Boolean granted) {
    this.granted = granted;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AndroidPermission androidPermission = (AndroidPermission) o;
    return Objects.equals(this.name, androidPermission.name) &&
        Objects.equals(this.granted, androidPermission.granted);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(name, granted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AndroidPermission {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    granted: ").append(toIndentedString(granted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
